from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name="Strategy", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=64, unique=True)), ("min_balance", models.DecimalField(decimal_places=2, max_digits=12)), ("primary_trades", models.PositiveSmallIntegerField(default=3)), ("max_steps", models.PositiveSmallIntegerField(default=5)), ("scaling_multiplier", models.DecimalField(decimal_places=2, default=2.3, max_digits=5)), ("payout_floor", models.DecimalField(decimal_places=2, default=72, max_digits=5)), ("enabled", models.BooleanField(default=True))]),
        migrations.CreateModel(name="TraderAccount", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("telegram_user_id", models.BigIntegerField(unique=True)), ("telegram_chat_id", models.BigIntegerField()), ("binodex_user_id", models.BigIntegerField(blank=True, null=True, unique=True)), ("email", models.EmailField(blank=True, max_length=254)), ("is_partner_client", models.BooleanField(default=False)), ("status", models.CharField(choices=[("new", "New"), ("oauth_pending", "OAuth pending"), ("confirmed", "Partner confirmed"), ("waiting_deposit", "Waiting for deposit"), ("ready", "Ready"), ("trading", "Trading"), ("reauth", "Reauthorization required"), ("blocked", "Blocked")], default="new", max_length=32)), ("access_token_encrypted", models.TextField(blank=True)), ("refresh_token_encrypted", models.TextField(blank=True)), ("token_expires_at", models.DateTimeField(blank=True, null=True)), ("real_balance", models.DecimalField(decimal_places=2, default=0, max_digits=14)), ("last_balance_check_at", models.DateTimeField(blank=True, null=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True))]),
        migrations.CreateModel(name="OAuthState", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("value", models.CharField(max_length=96, unique=True)), ("expires_at", models.DateTimeField()), ("used_at", models.DateTimeField(blank=True, null=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="oauth_states", to="trader.traderaccount"))]),
        migrations.CreateModel(name="TradingSession", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("stake", models.DecimalField(decimal_places=2, max_digits=12)), ("duration", models.PositiveIntegerField(help_text="seconds")), ("selected_asset_id", models.IntegerField(blank=True, null=True)), ("current_primary", models.PositiveSmallIntegerField(default=1)), ("current_step", models.PositiveSmallIntegerField(default=1)), ("status", models.CharField(choices=[("active", "Active"), ("paused", "Paused"), ("complete", "Complete"), ("stopped", "Stopped"), ("error", "Error")], default="active", max_length=16)), ("created_at", models.DateTimeField(auto_now_add=True)), ("ended_at", models.DateTimeField(blank=True, null=True)), ("note", models.TextField(blank=True)), ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sessions", to="trader.traderaccount")), ("strategy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="trader.strategy"))]),
        migrations.CreateModel(name="Trade", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("remote_id", models.BigIntegerField(unique=True)), ("asset_id", models.IntegerField()), ("symbol", models.CharField(blank=True, max_length=40)), ("action", models.CharField(max_length=4)), ("amount", models.DecimalField(decimal_places=2, max_digits=12)), ("payout", models.DecimalField(decimal_places=2, default=0, max_digits=6)), ("primary_number", models.PositiveSmallIntegerField()), ("step_number", models.PositiveSmallIntegerField()), ("status", models.CharField(default="open", max_length=16)), ("profit", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)), ("opened_at", models.DateTimeField(auto_now_add=True)), ("closed_at", models.DateTimeField(blank=True, null=True)), ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="trades", to="trader.tradingsession"))]),
    ]
