# Generated by Django 5.1.4 on 2026-09-27 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategy',
            options={'verbose_name_plural': 'Strategies'},
        ),
    ]
